=== yfons/RapidFXorg/settings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="settings">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="profiles">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="profile">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="id" type="xs:string" />
                    <xs:element name="activation">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="property">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="name" type="xs:string" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="properties">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="myMavenRepoReadUrl" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== yfons/RapidFXorg/settings.xml
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="settings.xsd">
    <profiles>
        <profile>
            <id>readMaven</id>
            <activation>
                <property>
                    <name>de.github.yfons.rapidfx</name>
                </property>
            </activation>
            <properties>
                <myMavenRepoReadUrl>https://mymavenrepo.com/repo/Fn0i73Weo588xIb0YPQp/</myMavenRepoReadUrl>
            </properties>
        </profile>
    </profiles>
</settings>
